In [1]:
import pandas as pd
pd.__version__

'2.1.4'

In [2]:
import numpy as np

# The Pandas Series Object

In [4]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [6]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
data[1]

0.5

In [8]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [9]:
#if we wish, we can use strings as an index:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [10]:
data['b']

0.5

In [4]:
population_dict = {'California': 38332521,
                    'Texas': 26448193,
                    'New York': 19651127,
                    'Florida': 19552860,
                    'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [12]:
 pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

# The Pandas DataFrame Object

In [7]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area
# Now that we have this along with the population Series from before, we can use a
# dictionary to construct a single two-dimensional object containing this information:

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [8]:
states = pd.DataFrame({'population': population, 'area': area})
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [9]:
states.columns

Index(['population', 'area'], dtype='object')

In [10]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [11]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [12]:
# Even if some keys in the dictionary are missing, Pandas will fill them in with NaN (i.e.,“Not a Number”) values:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [17]:
# One difference between Index objects and NumPy arrays is that indices are immutable
# This immutability (تغییرناپذیر) makes it safer to share indices between multiple DataFrames and
# arrays, without the potential for side effects from inadvertent index modification.
states.index[0]

'California'

In [18]:
states['California':'New York']

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297

In [19]:
states[0:2]

            population    area
California    38332521  423967
Texas         26448193  695662

# Indexers: loc (subset), iloc, and ix

data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

In [23]:
# explicit index when indexing
data[1]

'a'

In [24]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

Because of this potential confusion in the case of integer indexes, Pandas provides
some special indexer attributes that explicitly expose certain indexing schemes.
First, the loc attribute allows indexing and slicing that always references the explicit index:

In [25]:
data.loc[1]

'a'

In [26]:
data.loc[1:3]

1    a
3    b
dtype: object

The iloc attribute allows indexing and slicing that always references the implicit
Python-style index:

In [27]:
data.iloc[1]

'b'

In [28]:
data.iloc[1:3]

3    b
5    c
dtype: object

One guiding principle of Python code is that “explicit is better than implicit.”

The ix indexer allows a hybrid of these two approaches:
example: states.ix[:3, :'pop']

# Sort values

In [ ]:
df_sorted = df.sort_values("Salary" , ascending = True)

# Data Selection in DataFrame

In [29]:
# to add a new column:
states['density'] = states['population'] / states['area']
states

            population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

# Transpose DataFrame

In [31]:
states.T

,California,Texas,New York,Florida,Illinois
population,3.833252e+07,2.644819e+07,1.965113e+07,1.955286e+07,1.288214e+07
area,4.239670e+05,6.956620e+05,1.412970e+05,1.703120e+05,1.499950e+05
density,9.041393e+01,3.801874e+01,1.390767e+02,1.148061e+02,8.588376e+01

In [33]:
# while indexing refers to columns, slicing refers to rows:
states['Florida':'Illinois']

          population    area     density
Florida     19552860  170312  114.806121
Illinois    12882135  149995   85.883763

In [34]:
states[1:3]

          population    area     density
Texas       26448193  695662   38.018740
New York    19651127  141297  139.076746

In [35]:
states[states.density > 100]

          population    area     density
New York    19651127  141297  139.076746
Florida     19552860  170312  114.806121

# Ufuncs

Because Pandas is designed to work with NumPy, any NumPy ufunc will work on
Pandas Series and DataFrame objects.

In [36]:
np.exp(states)

C:\Users\sha.shojaei\AppData\Local\anaconda3\envs\health\Lib\site-packages\pandas\core\internals\blocks.py:366: RuntimeWarning: overflow encountered in exp
  result = func(self.values, **kwargs)

            population  area       density
California         inf   inf  1.846159e+39
Texas              inf   inf  3.245855e+16
New York           inf   inf  2.513410e+60
Florida            inf   inf  7.238768e+49
Illinois           inf   inf  1.989960e+37

# Index alignment in Series

In [37]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,'California': 423967}, name='area')
area

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

In [38]:
population = pd.Series({'California': 38332521, 'Texas': 26448193,'New York': 19651127}, name='population')
population

California    38332521
Texas         26448193
New York      19651127
Name: population, dtype: int64

In [39]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [42]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])

In [43]:
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [45]:
A.add(B , fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

# Index alignment in DataFrames

In [48]:
rng = np.random.RandomState(42)
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
A

    A   B
0   6  19
1  14  10

In [49]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))
B

   B  A  C
0  7  4  6
1  9  2  6
2  7  4  3

In [50]:
A + B

      A     B   C
0  10.0  26.0 NaN
1  16.0  19.0 NaN
2   NaN   NaN NaN

In [51]:
# Here we’ll fill with the mean of all values in A (which we compute by first stacking the rows of A):
fill = A.stack().mean()
A.add(B, fill_value=fill)

       A      B      C
0  10.00  26.00  18.25
1  16.00  19.00  18.25
2  16.25  19.25  15.25

Python operator Pandas method(s)
+               add()
-               sub(), subtract()
*               mul(), multiply()
/               truediv(), div(), divide()
//              floordiv()
%               mod()
**              pow()

# Handling Missing Data

we’ll refer to missing data in general as null, NaN, or NA values.

## None: Pythonic missing data

In [52]:
# Because None is a Python object, it cannot be used in any arbitrary NumPy/Pandas array, but only in arrays with data type 'object' 
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

The use of Python objects in an array also means that if you perform aggregations
like sum() or min() across an array with a None value, you will generally get an error:

In [53]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

## NaN: Missing numerical data

In [58]:
# NaN is specifically a floating-point value
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [55]:
 1 + np.nan

nan

In [56]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [57]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

NaN and None in Pandas:

In [59]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

****Pandas handling of NAs by type****
Typeclass Conversion when storing NAs NA sentinel value
floating  No change                   np.nan
object    No change                   None or np.nan
integer   Cast to float64             np.nan
boolean   Cast to object              None or np.nan

* Keep in mind that in Pandas, string data is always stored with an object dtype.

## Operating on Null Values

isnull(): Generate a Boolean mask indicating missing values
notnull(): Opposite of isnull()
dropna(): Return a filtered version of the data
fillna(): Return a copy of the data with missing values filled or imputed

### Detecting null values => isnull() isna() and notnull()

In [61]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull() #isna()

0    False
1     True
2    False
3     True
dtype: bool

In [63]:
data[data.isnull()]

1     NaN
3    None
dtype: object

In [64]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [65]:
data[data.notnull()]

0        1
2    hello
dtype: object

### Dropping null values => dropna() and fillna()

fillna() (which fills in NA values

In [66]:
data.dropna() # removes NA values

0        1
2    hello
dtype: object

We cannot drop single values from a DataFrame; we can only drop full rows or full
columns. Depending on the application, you might want one or the other, so
dropna() gives a number of options for a DataFrame.

In [67]:
df = pd.DataFrame([[1, np.nan, 2],
                    [2, 3, 5],
                    [np.nan, 4, 6]])
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [68]:
df.dropna()

     0    1  2
1  2.0  3.0  5

In [69]:
df.dropna(axis='columns')

   2
0  2
1  5
2  6

In [70]:
df[3] = np.nan
df

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [72]:
df.dropna(axis='columns', how='all') #only drop rows/columns that are all null values

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [73]:
df.dropna(axis='rows', thresh=3) #the thresh parameter lets you specify a minimum number of non-null values for the row/column to be kept

     0    1  2   3
1  2.0  3.0  5 NaN

### Filling null values => fillna()

In [74]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [75]:
data.fillna(0) # fill NA entries with a single value, such as zero

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [77]:
data.fillna(method='ffill') # specify a forward-fill to propagate the previous value forward

C:\Users\sha.shojaei\AppData\Local\Temp\ipykernel_10012\1510172377.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill') # specify a forward-fill to propagate the previous value forward

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [78]:
data.fillna(method='bfill') # specify a back-fill to propagate the next values backward

C:\Users\sha.shojaei\AppData\Local\Temp\ipykernel_10012\1956276469.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill') # specify a back-fill to propagate the next values backward

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [79]:
df

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [80]:
 df.fillna(method='ffill', axis=1)

C:\Users\sha.shojaei\AppData\Local\Temp\ipykernel_10012\2718087340.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', axis=1)

     0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

# Hierarchical Indexing or multi-indexing

In [81]:
 index = [('California', 2000), ('California', 2010),
            ('New York', 2000), ('New York', 2010),
            ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
                18976457, 19378102,
                20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [82]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [83]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [84]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

## MultiIndex as extra dimension

In [85]:
pop_df = pop.unstack()
pop_df

                2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [86]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

if you pass a dictionary with appropriate tuples as keys, Pandas will auto‐
matically recognize this and use a MultiIndex by default:

In [87]:
pd.Series(pop)

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

## Explicit MultiIndex constructors

In [88]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [89]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [90]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

## MultiIndex level names

In [93]:
pop.index.names = ['state', 'year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [94]:
pop['California', 2000]

33871648

In [95]:
pop['California']

year
2000    33871648
2010    37253956
dtype: int64

In [96]:
pop.loc['California':'New York']

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [97]:
pop[:, 2000]

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [98]:
pop[pop > 22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

## Rearranging Multi-Indices

# MultiIndex not being sorted

In [100]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.369377
      2      0.753373
c     1      0.536775
      2      0.091791
b     1      0.877718
      2      0.263000
dtype: float64

In [101]:
data = data.sort_index()
data

char  int
a     1      0.369377
      2      0.753373
b     1      0.877718
      2      0.263000
c     1      0.536775
      2      0.091791
dtype: float64

In [102]:
#With the index sorted in this way, partial slicing will work as expected:
data['a':'b']

char  int
a     1      0.369377
      2      0.753373
b     1      0.877718
      2      0.263000
dtype: float64

## Stacking and unstacking indices

In [103]:
pop.unstack(level=0)

state  California  New York     Texas
year
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [104]:
pop.unstack(level=1)

year            2000      2010
state
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [105]:
pop.unstack().stack()

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

## Index setting and resetting

In [106]:
pop_flat = pop.reset_index(name='population')
pop_flat

        state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [107]:
pop_flat.set_index(['state', 'year'])

                 population
state      year
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

## Data Aggregations on Multi-Indices

In [ ]:
# data_mean = health_data.mean(level='year')

In [109]:
# data_mean.mean(axis=1, level='type') # aking use of the axis keyword, we can take the mean among levels on the columns

# Combining Datasets: Concat and Append

In [111]:
def make_df(cols, ind):
#Quickly make a DataFrame
    data = {c: [str(c) + str(i) for i in ind]
    for c in cols}
    return pd.DataFrame(data, ind)
# example DataFrame
make_df('ABC', range(3))

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

## Recall: Concatenation of NumPy Arrays

In [112]:
x = [[1, 2],
    [3, 4]]
np.concatenate([x, x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

# Signature in Pandas v0.18
pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False,
keys=None, levels=None, names=None, verify_integrity=False,
copy=True)

In [114]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [116]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
print(df3); print(df4); print(pd.concat([df3, df4]))

    A   B
0  A0  B0
1  A1  B1
    C   D
0  C0  D0
1  C1  D1
     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1

## Duplicate indices

In [ ]:
# 1- Catching the repeats as an error
try:
pd.concat([x, y], verify_integrity=True)
except ValueError as e:
print("ValueError:", e)

In [ ]:
# 2- Ignoring the index
# Sometimes the index itself does not matter, and you would prefer
# it to simply be ignored. You can specify this option using the ignore_index flag. With
# this set to True, the concatenation will create a new integer index for the resulting Series
print(x); print(y); print(pd.concat([x, y], ignore_index=True))

In [ ]:
# 3 - Adding MultiIndex keys
print(x); print(y); print(pd.concat([x, y], keys=['x', 'y']))

In [118]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
print(df5); print(df6); print(pd.concat([df5, df6]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [120]:
#  By default, the join is a union of the input columns (join='outer'), but we can change this to an intersection of the columns using join='inner':
print(pd.concat([df5, df6], join='inner'))

    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

## The append() method

In [125]:
# print(df5); print(df6); print(df5.append(df6)) # as same as pd.concat([df5, df6])

# Combining Datasets: Merge and Join

Categories of Joins (pd.merge()) :
1- one-to-one
2- many-to-one
3- many-to-many

In [126]:
# example of one-to-one
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
print(df1); print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [127]:
df3 = pd.merge(df1, df2)
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

The pd.merge() function recognizes that each DataFrame has an “employee” column,
and automatically joins using this column as a key

In [128]:
# example of many-to-one
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
print(df3); print(df4); print(pd.merge(df3, df4))

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve
  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [129]:
# example of many-to-many
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting','Engineering', 'Engineering', 'HR', 'HR'], 
                    'skills': ['math', 'spreadsheets', 'coding', 'linux','spreadsheets', 'organization']})
print(df1); print(df5); print(pd.merge(df1, df5))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization
  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [130]:
 print(df1); print(df2); print(pd.merge(df1, df2, on='employee'))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014
  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [131]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
print(df1); print(df3);
print(pd.merge(df1, df3, left_on="employee", right_on="name"))

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000
  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [132]:
pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1)

  employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [133]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
print(df1a); print(df2a)

                group
employee
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
          hire_date
employee
Lisa           2004
Bob            2008
Jake           2012
Sue            2014

In [134]:
# You can use the index as the key for merging by specifying the left_index and/or
# right_index flags in pd.merge():

print(df1a); print(df2a);
print(pd.merge(df1a, df2a, left_index=True, right_index=True))

                group
employee
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
          hire_date
employee
Lisa           2004
Bob            2008
Jake           2012
Sue            2014
                group  hire_date
employee
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [135]:
print(df1a); print(df2a); print(df1a.join(df2a)) #  DataFrames implement the join() method, which performs a merge that defaults to joining on indices:

                group
employee
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
          hire_date
employee
Lisa           2004
Bob            2008
Jake           2012
Sue            2014
                group  hire_date
employee
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

## Specifying Set Arithmetic for Joins

intersection of the two sets of inputs; this is what is known as an inner join.
We can specify this explicitly using the how keyword,
which defaults to 'inner':

In [4]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                    columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                    columns=['name', 'drink'])
print(df6); print(df7); print(pd.merge(df6, df7))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
     name drink
0    Mary  wine
1  Joseph  beer
   name   food drink
0  Mary  bread  wine

In [5]:
pd.merge(df6, df7, how='inner') # intersection of the two sets of inputs

   name   food drink
0  Mary  bread  wine

In [6]:
print(pd.merge(df6, df7, how='outer')) # returns a join over the union of the input columns, and fills in all missing values with NAs

     name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer

In [7]:
print(pd.merge(df6, df7, how='left'))

    name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

In [8]:
print(pd.merge(df6, df7, how='right'))

     name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer

## Overlapping Column Names: The suffixes Keyword

In [9]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'rank': [3, 1, 4, 2]})
print(df8); print(df9); print(pd.merge(df8, df9, on="name"))

   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4
   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2
   name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

Because the output would have two conflicting column names, the merge function
automatically appends a suffix _x or _y to make the output columns unique. If these
defaults are inappropriate, it is possible to specify a custom suffix using the suffixes
keyword:

In [10]:
print(pd.merge(df8, df9, on="name", suffixes=["_L", "_R"]))

   name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

# Aggregation and Grouping

In [11]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets.shape

(1035, 6)

In [12]:
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [16]:
rng = np.random.RandomState(42)
df = pd.DataFrame({'A': rng.rand(5),
                    'B': rng.rand(5)})
df

          A         B
0  0.374540  0.155995
1  0.950714  0.058084
2  0.731994  0.866176
3  0.598658  0.601115
4  0.156019  0.708073

## Simple Aggregation in Pandas: sum(), mean()

In [17]:
df.sum()

A    2.811925
B    2.389442
dtype: float64

In [18]:
df.mean()

A    0.562385
B    0.477888
dtype: float64

In [19]:
df.mean(axis='columns')

0    0.265267
1    0.504399
2    0.799085
3    0.599887
4    0.432046
dtype: float64

In [20]:
planets.dropna().describe()

          number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

Aggregation        Description
count()            Total number of items
first(), last()    First and last item
mean(), median()   Mean and median
min(), max()       Minimum and maximum
std(), var()       Standard deviation and variance
mad()              Mean absolute deviation
prod()             Product of all items
sum()              Sum of all items

## GroupBy: Split, Apply, Combine

• The split step involves breaking up and grouping a DataFrame depending on the value of the specified key.
• The apply step involves computing some function, usually an aggregate, transformation, or filtering, within the individual groups.
• The combine step merges the results of these operations into an output array.

In [21]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                    'data': range(6)}, columns=['key', 'data'])
df

  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [23]:
# We can compute the most basic split-apply-combine operation with the groupby()
# method of DataFrames, passing the name of the desired key column:
df.groupby('key').sum()

     data
key
A       3
B       5
C       7

In [ ]:
df.groupby('key').count()

### Column indexing

In [24]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

### Iteration over groups

In [25]:
for (method, group) in planets.groupby('method'):
    print("{0:30s} shape={1}".format(method, group.shape))

Astrometry                     shape=(2, 6)
Eclipse Timing Variations      shape=(9, 6)
Imaging                        shape=(38, 6)
Microlensing                   shape=(23, 6)
Orbital Brightness Modulation  shape=(3, 6)
Pulsar Timing                  shape=(5, 6)
Pulsation Timing Variations    shape=(1, 6)
Radial Velocity                shape=(553, 6)
Transit                        shape=(397, 6)
Transit Timing Variations      shape=(4, 6)

### Dispatch methods

In [26]:
planets.groupby('method')['year'].describe().unstack()

       method
count  Astrometry                          2.0
       Eclipse Timing Variations           9.0
       Imaging                            38.0
       Microlensing                       23.0
       Orbital Brightness Modulation       3.0
                                         ...
max    Pulsar Timing                    2011.0
       Pulsation Timing Variations      2007.0
       Radial Velocity                  2014.0
       Transit                          2014.0
       Transit Timing Variations        2014.0
Length: 80, dtype: float64

## Aggregate, filter, transform, apply

In [28]:
# GroupBy objects have aggregate(), filter(), transform(), and apply() methods
rng = np.random.RandomState(0)
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data1': range(6),
                   'data2': rng.randint(0, 10, 6)},
                    columns = ['key', 'data1', 'data2'])
df

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

### Aggregation

In [33]:
df.groupby('key').aggregate(["min", "median" , "max"])

    data1            data2
      min median max   min median max
key
A       0    1.5   3     3    4.0   5
B       1    2.5   4     0    3.5   7
C       2    3.5   5     3    6.0   9

In [30]:
 df.groupby('key').aggregate({'data1': 'min',
                              'data2': 'max'})

     data1  data2
key
A        0      5
B        1      7
C        2      9

### Filtering

In [34]:
def filter_func(x):
    return x['data2'].std() > 4
    
print(df);
print(df.groupby('key').std());
print(df.groupby('key').filter(filter_func))

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9
       data1     data2
key
A    2.12132  1.414214
B    2.12132  4.949747
C    2.12132  4.242641
  key  data1  data2
1   B      1      0
2   C      2      3
4   B      4      7
5   C      5      9

### Transformation

In [35]:
df.groupby('key').transform(lambda x: x - x.mean())

   data1  data2
0   -1.5    1.0
1   -1.5   -3.5
2   -1.5   -3.0
3    1.5   -1.0
4    1.5    3.5
5    1.5    3.0

### Apply

In [36]:
def norm_by_data2(x):
    # x is a DataFrame of group values
    x['data1'] /= x['data2'].sum()
    return x

print(df.groupby('key').apply(norm_by_data2))

      key     data1  data2
key
A   0   A  0.000000      5
    3   A  0.375000      3
B   1   B  0.142857      0
    4   B  0.571429      7
C   2   C  0.166667      3
    5   C  0.416667      9

# Pivot Tables

In [37]:
import numpy as np
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')

In [38]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [39]:
titanic.groupby('sex')[['survived']].mean()

        survived
sex
female  0.742038
male    0.188908

In [40]:
titanic.groupby(['sex', 'class'])['survived'].aggregate('mean').unstack()

C:\Users\sha.shojaei\AppData\Local\Temp\ipykernel_10704\2603839867.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(['sex', 'class'])['survived'].aggregate('mean').unstack()

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

## Pivot Table Syntax

DataFrame.pivot_table(data, values=None, index=None, columns=None,
                      aggfunc='mean', fill_value=None, margins=False,
                      dropna=True, margins_name='All')

In [41]:
titanic.pivot_table('survived', index='sex', columns='class')

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

## Multilevel pivot tables

In [42]:
age = pd.cut(titanic['age'], [0, 18, 80])
titanic.pivot_table('survived', ['sex', age], 'class')

class               First    Second     Third
sex    age
female (0, 18]   0.909091  1.000000  0.511628
       (18, 80]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 80]  0.375000  0.071429  0.133663

In [43]:
fare = pd.qcut(titanic['fare'], 2)
titanic.pivot_table('survived', ['sex', age], [fare, 'class'])

fare            (-0.001, 14.454]                     (14.454, 512.329]  \
class                      First    Second     Third             First
sex    age
female (0, 18]               NaN  1.000000  0.714286          0.909091
       (18, 80]              NaN  0.880000  0.444444          0.972973
male   (0, 18]               NaN  0.000000  0.260870          0.800000
       (18, 80]              0.0  0.098039  0.125000          0.391304

fare
class              Second     Third
sex    age
female (0, 18]   1.000000  0.318182
       (18, 80]  0.914286  0.391304
male   (0, 18]   0.818182  0.178571
       (18, 80]  0.030303  0.192308

In [44]:
titanic.pivot_table(index='sex', columns='class', aggfunc={'survived':sum, 'fare':'mean'})

C:\Users\sha.shojaei\AppData\Local\Temp\ipykernel_10704\2535883282.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  titanic.pivot_table(index='sex', columns='class', aggfunc={'survived':sum, 'fare':'mean'})

              fare                       survived
class        First     Second      Third    First Second Third
sex
female  106.125798  21.970121  16.118810       91     70    72
male     67.226127  19.741782  12.661633       45     17    47

# Vectorized String Operations

In [45]:
data = ['peter', 'Paul', 'MARY', 'gUIDO']
names = pd.Series(data)
names

0    peter
1     Paul
2     MARY
3    gUIDO
dtype: object

In [46]:
names.str.capitalize() # capitalize all the entries, while skipping over any missing values

0    Peter
1     Paul
2     Mary
3    Guido
dtype: object

Pandas str methods: 
len() lower() translate() islower()
ljust() upper() startswith() isupper()
rjust() find() endswith() isnumeric()
center() rfind() isalnum() isdecimal()
zfill() index() isalpha() split()
strip() rindex() isdigit() rsplit()
rstrip() capitalize() isspace() partition()
lstrip() swapcase() istitle() rpartition()

In [47]:
monte = pd.Series(['Graham Chapman', 'John Cleese', 'Terry Gilliam','Eric Idle', 'Terry Jones', 'Michael Palin'])

In [48]:
monte.str.lower()

0    graham chapman
1       john cleese
2     terry gilliam
3         eric idle
4       terry jones
5     michael palin
dtype: object

In [49]:
monte.str.len()

0    14
1    11
2    13
3     9
4    11
5    13
dtype: int64

In [50]:
monte.str.startswith('T')

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [51]:
monte.str.split()

0    [Graham, Chapman]
1       [John, Cleese]
2     [Terry, Gilliam]
3         [Eric, Idle]
4       [Terry, Jones]
5     [Michael, Palin]
dtype: object

## Methods using regular expressions

Method      Description
match()     Call re.match() on each element, returning a Boolean.
extract()   Call re.match() on each element, returning matched groups as strings.
findall()   Call re.findall() on each element.
replace()   Replace occurrences of pattern with some other string.
contains()  Call re.search() on each element, returning a Boolean.
count()     Count occurrences of pattern.
split()     Equivalent to str.split(), but accepts regexps.
rsplit()    Equivalent to str.rsplit(), but accepts regexps.

In [53]:
# extract the first name from each by asking for a contiguous group of characters at the beginning of each element
monte.str.extract('([A-Za-z]+)')

         0
0   Graham
1     John
2    Terry
3     Eric
4    Terry
5  Michael

In [54]:
# start and end with a consonant, making use of the start-of-string (^) and end-of-string ($) regular expression characters
monte.str.findall(r'^[^AEIOU].*[^aeiou]$')

0    [Graham Chapman]
1                  []
2     [Terry Gilliam]
3                  []
4       [Terry Jones]
5     [Michael Palin]
dtype: object

## Miscellaneous methods

Method           Description
get()            Index each element
slice()          Slice each element
slice_replace()  Replace slice in each element with passed value
cat()            Concatenate strings
repeat()         Repeat values
normalize()      Return Unicode form of string
pad()            Add whitespace to left, right, or both sides of strings
wrap()           Split long strings into lines with length less than a given width
join()           Join strings in each element of the Series with passed separator
get_dummies()    Extract dummy variables as a DataFrame

In [57]:
monte.str.slice(0, 3)

0    Gra
1    Joh
2    Ter
3    Eri
4    Ter
5    Mic
dtype: object

In [58]:
monte.str[0:3]

0    Gra
1    Joh
2    Ter
3    Eri
4    Ter
5    Mic
dtype: object

In [59]:
# to extract the last name of each entry, we can combine split() and get()
monte.str.split().str.get(-1)

0    Chapman
1     Cleese
2    Gilliam
3       Idle
4      Jones
5      Palin
dtype: object

### get_dummies()

This is useful when your data has a column containing some sort of coded indicator.
For example, we might have a dataset that contains information in the form of codes,
such as A=“born in America,” B=“born in the United Kingdom,” C=“likes cheese,” D=“likes spam”:

In [60]:
full_monte = pd.DataFrame({'name': monte,
                            'info': ['B|C|D', 'B|D', 'A|C', 'B|D', 'B|C', 'B|C|D']})
full_monte

             name   info
0  Graham Chapman  B|C|D
1     John Cleese    B|D
2   Terry Gilliam    A|C
3       Eric Idle    B|D
4     Terry Jones    B|C
5   Michael Palin  B|C|D

In [61]:
full_monte['info'].str.get_dummies('|')

   A  B  C  D
0  0  1  1  1
1  0  1  0  1
2  1  0  1  0
3  0  1  0  1
4  0  1  1  0
5  0  1  1  1

# Working with Time Series

In [62]:
from datetime import datetime
datetime(year=2015, month=7, day=4)

datetime.datetime(2015, 7, 4, 0, 0)

In [63]:
from dateutil import parser
date = parser.parse("4th of July, 2015")
date

datetime.datetime(2015, 7, 4, 0, 0)

In [64]:
date.strftime('%A') # printing the day of the week

'Saturday'

In [65]:
 import numpy as np
date = np.array('2015-07-04', dtype=np.datetime64)
date

array('2015-07-04', dtype='datetime64[D]')

In [66]:
np.datetime64('2015-07-04')

numpy.datetime64('2015-07-04')

In [67]:
np.datetime64('2015-07-04 12:00')

numpy.datetime64('2015-07-04T12:00')

In [68]:
np.datetime64('2015-07-04 12:59:59.50', 'ns')

numpy.datetime64('2015-07-04T12:59:59.500000000')

## Dates and times in Pandas: Best of both worlds

In [69]:
import pandas as pd
date = pd.to_datetime("4th of July, 2015")
date

Timestamp('2015-07-04 00:00:00')

In [70]:
date.strftime('%A')

'Saturday'

In [71]:
date + pd.to_timedelta(np.arange(12), 'D')

DatetimeIndex(['2015-07-04', '2015-07-05', '2015-07-06', '2015-07-07',
               '2015-07-08', '2015-07-09', '2015-07-10', '2015-07-11',
               '2015-07-12', '2015-07-13', '2015-07-14', '2015-07-15'],
              dtype='datetime64[ns]', freq=None)

## Pandas Time Series: Indexing by Time

In [72]:
index = pd.DatetimeIndex(['2014-07-04', '2014-08-04',
                          '2015-07-04', '2015-08-04'])
data = pd.Series([0, 1, 2, 3], index=index)
data

2014-07-04    0
2014-08-04    1
2015-07-04    2
2015-08-04    3
dtype: int64

In [73]:
data['2014-07-04':'2015-07-04']

2014-07-04    0
2014-08-04    1
2015-07-04    2
dtype: int64

In [74]:
data['2015']

2015-07-04    2
2015-08-04    3
dtype: int64

## Pandas Time Series Data Structures

In [76]:
date.to_period('D') # use 'D' to indicate daily frequency

Period('2015-07-04', 'D')

In [77]:
pd.date_range('2015-07-03', '2015-07-10') #for timestamps

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [78]:
pd.date_range('2015-07-03', periods=8)

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [79]:
 pd.date_range('2015-07-03', periods=8, freq='H') #  a range of hourly timestamps

DatetimeIndex(['2015-07-03 00:00:00', '2015-07-03 01:00:00',
               '2015-07-03 02:00:00', '2015-07-03 03:00:00',
               '2015-07-03 04:00:00', '2015-07-03 05:00:00',
               '2015-07-03 06:00:00', '2015-07-03 07:00:00'],
              dtype='datetime64[ns]', freq='H')

In [80]:
pd.period_range('2015-07', periods=8, freq='M') #for Monthly periods

PeriodIndex(['2015-07', '2015-08', '2015-09', '2015-10', '2015-11', '2015-12',
             '2016-01', '2016-02'],
            dtype='period[M]')

In [81]:
pd.timedelta_range(0, periods=10, freq='H') # a sequence of durations increasing by an hour

TimedeltaIndex(['0 days 00:00:00', '0 days 01:00:00', '0 days 02:00:00',
                '0 days 03:00:00', '0 days 04:00:00', '0 days 05:00:00',
                '0 days 06:00:00', '0 days 07:00:00', '0 days 08:00:00',
                '0 days 09:00:00'],
               dtype='timedelta64[ns]', freq='H')